apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-node-app
  template:
    metadata:
      labels:
        app: k8s-node-app
    spec:
      containers:
      - name: k8s-node-app
        image: srikanth968/k8s-node-app:latest
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10

